### ISSUE TITLE
Incorrect Hotkey In Description for MacOS

### ISSUE THREAD

**Issue by hunterwilhelm** [fabiosangregorio/google-calendar-quick-duplicate#11]
Thank you so much for merging and reformatting the code. It works great! 

However, the [extension page](https://chrome.google.com/webstore/detail/google-calendar-quick-dup/belnijodgolpgmpahmdkjbjehbobnfpd) says that the MacOS hotkey is <kbd>cmd</kbd>. However it should be <kbd>option</kbd>. Small detail, but we don't want the mac users to be confused. I tested on a mac to make sure.

Suggested change:

> You can also quickly duplicate an event by holding alt (![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) ~~cmd~~ on Mac OS) while clicking the event.

> You can also quickly duplicate an event by holding alt (![#c5f015](https://via.placeholder.com/15/c5f015/000000?text=+) **option** on Mac OS) while clicking the event.

**Comment by fabiosangregorio** [comment]
Nice catch, thank you so much! 

Updated in d605390 as well as on the extension page. (will be delivered in a couple of days)
