### ISSUE TITLE
Duplicate icon hardly visible when event has an image

### ISSUE THREAD

**Issue by coreOf** [fabiosangregorio/google-calendar-quick-duplicate#15]
### Description

> In event quick view, when the event has an image automatically generated by Google Calendar, the icon for quick duplication is not visible. It does not change the color, and is also missing a background circle.   

### Reproduction

> Create an event with keywords like gym, dinner or coffee in the title and Google Calendar will automatically generate an image for the event that will be shown in event quick view

> Example:
![image](https://user-images.githubusercontent.com/42045607/219233773-91a283af-3ae8-4279-ad8d-32f0997ec170.png)

> The whole list of keywords can be found here: http://www.internetbestsecrets.com/2019/09/google-calendar-event-images.html

### Environment

- **Version of this library used:** 1.1.0
- **OS:** MS Windows 10 Pro, Version 22H2
- **Browser:** Google Chrome, Version 109.0.5414.120 (Official Build)

**Comment by fabiosangregorio** [comment]
Hey! Thanks for notifying this issue 🙏🏻 The fixed is merged and will be released soon.
