### ISSUE TITLE
Duplicate Event doesn't do anything as of today.

### ISSUE THREAD

**Issue by notwatermango** [fabiosangregorio/google-calendar-quick-duplicate#19]
### Description

Extension doesn't work. I use this extension daily and as of today it doesn't do anything when clicking duplicate event.

### Reproduction

Click duplicate event

### Environment

Version: 1.1.0
Chrome: 113.0.5672.127 (Official Build) (64-bit)

**Comment by HLongYT** [comment]
Same with me. Dupplicate Icon on Event isn' working too

**Comment by belldragon7** [comment]
Same here

**Comment by notwatermango** [comment]
Dear @fabiosangregorio, please check my PR as the extension is currently unusable.

**Comment by belldragon7** [comment]
@notwatermango Your Pull request fixed it. Thank you!
