### ISSUE TITLE
Dead - No longer working

### ISSUE THREAD

**Issue by danieljgullo** [fabiosangregorio/google-calendar-quick-duplicate#22]
### Description

Quick duplicate has been working really well for years.  Now, it is NOT working as of Chrome Version 119.0.6045.200 (Official Build) (64-bit) released 11/28/2023.  I think the plugin needs to be updated or something.  It just stopped working in the last few days since this official version of Chrome was deployed.

### Reproduction

Open Google calendar.
Click on a an event or appointment.
Sometimes the Quick Duplicate icon is there, sometimes it is not.  This is intermittent.
If the icon is there, clicking it does nothing, whereas before, it created a duplicate copy of the event.

**Comment by Felicis** [comment]
I can confirm it does not work with older chrome versions either, namely `114.0.5735.198` and `112.0.5615.49`
