### ISSUE TITLE
Add keyboard shortcut to duplicate quickly (Feature request)

### ISSUE THREAD

**Issue by adithya-r-prabhu** [fabiosangregorio/google-calendar-quick-duplicate#7]
Your Extension is Super good but to duplicate we have to follow 2 steps right .

This can be reduced by making a keyboard shortcut like pressing **alt** and **pressing on the event by mouse** duplicates it .

Thank you

**Comment by hunterwilhelm** [comment]
I agree, we need a shortcut.

**Comment by fabiosangregorio** [comment]
Hi @adithya-r-prabhu, @hunterwilhelm 👋🏻 
Nice proposal, I like it! Unfortunately as of now I don't have time to further develop the extension, but if you are knowledgable in JS and would like to put together a PR for this I would be more than happy to discuss it there and merge it!
Happy holidays 🎄

**Comment by adithya-r-prabhu** [comment]
> Hi @adithya-r-prabhu, @hunterwilhelm 👋🏻 Nice proposal, I like it! Unfortunately as of now I don't have time to further develop the extension, but if you are knowledgable in JS and would like to put together a PR for this I would be more than happy to discuss it there and merge it! Happy holidays christmas_tree

Hi👋,
I dont know JavaScript much , but added a shortcut that is **pressing "."(period key) would duplicate the event.**
![image](https://user-images.githubusercontent.com/83577193/147598613-2cbce864-2d39-4034-9fa7-d60e68e9a961.png)

The fork can be found [here](https://github.com/adithya-r-prabhu/google-calendar-quick-duplicate) 
I dont think this is the best solution([according to my initial comment](https://github.com/fabiosangregorio/google-calendar-quick-duplicate/issues/7#issue-1062661034))  but if @fabiosangregorio likes to add it go ahead.
Happy holidays 🎅 all

**Comment by fabiosangregorio** [comment]
Released in 1.1.0
