### ISSUE TITLE
Events break when named "Lunch"

### ISSUE THREAD

**Issue by hunterwilhelm** [fabiosangregorio/google-calendar-quick-duplicate#8]
### Description

I named an event "Lunch" and the button doesn't work as expected because it has a background image that is messing up the CSS or HTML.

### Reproduction

1. Name an event "Lunch"
2. Try to duplicate it
3. You'll see that it looks strange and doesn't work when you click it.

### Pictures

What it looks like without hover
<img width="473" alt="Screen Shot 2021-12-08 at 10 45 41 AM" src="https://user-images.githubusercontent.com/71348224/145257994-381d928f-e825-49cd-920b-abaaf9a78a99.png">

With hover
<img width="463" alt="Screen Shot 2021-12-08 at 10 45 48 AM" src="https://user-images.githubusercontent.com/71348224/145258022-afac12bc-e22e-41e0-8ffa-d0f4d2218d8c.png">

Clicking option actually triggers it instead of duplicate.
<img width="466" alt="Screen Shot 2021-12-08 at 10 46 28 AM" src="https://user-images.githubusercontent.com/71348224/145258032-c725f430-8ddf-45a8-9509-f7578b221368.png">

### Environment
- Version of extension: 1.0.3
- macOS Big Sur
- Chrome Version 96.0.4664.55 (Official Build) (x86_64)

**Comment by fabiosangregorio** [comment]
Hey @hunterwilhelm! 
Nice catch, I think this may be due to a low z-index on the duplicate icon. As I mentioned in another issue, unfortunately as of now I'm too busy to further develop the extension, but if you are willing to put together a PR I'd be more than happy to help you out there and merge it!
Happy holidays 🎄

**Comment by fabiosangregorio** [comment]
Released in 1.1.0
